### PR TITLE
Support help message for argument

### LINKED ISSUE #2983: Add help kwarg to argument parameter
We are now open to a PR for adding a help kwarg to arguments in the same way that there is for options and adjusting the help pages to account for this. 

[Help Pages](https://click.palletsprojects.com/en/stable/documentation/#help-pages)

```
@click.command()
@click.argument('name', help='The name to print')
@click.option('--count', default=1, help='number of greetings')
def hello(name: str, count: int):
    """This script prints hello and a name one or more times."""
    for x in range(count):
        if name:
            click.echo(f"Hello {name}!")
        else:
            click.echo("Hello!")
```

### PR DESCRIPTION
**Pull request by Ralph-Wang**
1. Support help message for argument
2. Add UT case for message
3. Fix other failed cases as there are more messages printed.

### CODE REVIEW

**Comment by mwgamble** [comment]
This looks really good. I'm not sure if it should be part of this pull request, but another great addition would be automatically displaying all available choices for parameters of type `Choice`.

**Comment by davidism** [comment]
I'm fairly sure this isn't supported on purpose. I think the docs mention that you should document required args in the docstring (the help text for the command itself.

**Comment by mwgamble** [comment]
I have a program with multiple commands where one of the required arguments is of type `Choice`, and can take over 20 different values. I don't want to have to list those out manually, I'd much prefer it if the help text generator could do that for me given it should already have access to the values.

**Comment by dsully** [comment]
I'm in favor of this patch. It's always struck me as odd that arguments couldn't have help specified like options could.

**Comment by davidism** [comment]
http://click.pocoo.org/5/documentation/#help-texts

> Arguments cannot be documented this way. This is to follow the general convention of Unix tools of using arguments for only the most necessary things and to document them in the introduction text by referring to them by name.

@untitaker opinion?

**Comment by untitaker** [comment]
I agree with the docs. If the arguments are not documented as part of the command's action then they should probably be options as they appear to be inessential to the core functionality

**Comment by Ralph-Wang** [comment]
If we don't want independent help text on screen, how about support the argument in the decorator but merge the message to the command description just like
```
# command ARGUMENT

command description and ARGUMENT(help message for argument)
```

**Comment by untitaker** [comment]
So @mwgamble I am pretty sure that you can generate the docstring programmatically in your case. I am not sure if you'd be satisfied with how click would format your 20 possible values in any case

@Ralph-Wang and @mwgamble could you give me a concrete example where you would need this feature? I am pretty sure that in such cases custom formatting is better than relying on click.

**Comment by mwgamble** [comment]
@untitaker That's a fair point. I was envisaging some kind of default output when no explicit help text is provided, for example:

    param1              Possible choices: choice1, choice2, choice3, choice4

**Comment by Ralph-Wang** [comment]
@untitaker It's pretty fair to generate docstring ourselves. But if we support help message in argument, we can make the message more close to the argument on the code side.

**Comment by davidism** [comment]
At this point I'm unwilling to change Click's handling of this.

**Comment by briancappello** [comment]
It's possible to extend `click` yourself if you want to support this feature. [Example code](https://github.com/pallets/click/issues/587#issuecomment-410097642)

**Pull request closed without merging**
