### PR TITLE
Changelog for 7.0

### PR DESCRIPTION
**Pull request by jcrotts**
https://github.com/pallets/click/issues/1038

### CODE REVIEW

**Comment by zacbir** [comment]
Excellent, thanks, Jay

**Comment by jcrotts** [comment]
Still working on it, got some more changes to add :)

**Comment by zacbir** [comment]
Sorry about that. I’ll take a further look when you’re finished.

Zac

**Comment by jcrotts** [comment]
No worries, I should have put a WIP tag.

**Pull request merged**
