### PR TITLE
Travis: use "set -e" to exit script in case of errors

### PR DESCRIPTION
**Pull request by blueyed**
Via https://github.com/pallets/click/commit/b471d346e93b818d7c8a87d8cee9e0705435ac19#commitcomment-25568443.

### CODE REVIEW

**Comment by stefreak** [comment]
I cherry-picked this into #889 and now it fails as it's supposed to be :) Seems to be working. 👍

**Comment by stefreak** [comment]
@mitsuhiko this really should be merged, because right now the tests are always green, even if they actually fail. According to the contributors page, you did the most commits, that's why I'm mentioning you.

**Comment by blueyed** [comment]
Ping @untitaker.

**Comment by mitsuhiko** [comment]
Indeed. Agreed.

**Pull request merged**
