### PR TITLE
Add no_args_is_help to click.Command

### LINKED ISSUE #1156: explicitly print help when no arguments are given
Hi,

I would like to explicitly print **full** help for my script if no arguments are given. The code:
```python
@click.command()
@click.argument('input_dir', type=click.Path(exists=True))
@click.argument('output_dir', type=click.Path(exists=True))
@click.option('-fc', 'fix_coord_chars', is_flag=True, help='fix wrong characters used in coordinates definitions')
@click.option('-fl', 'fix_lon_lat', is_flag=True, help='enable swapping of lon and lat if switched. Configure list of accepted values in config.py')
@click.option('-c', 'check_lon_lat', is_flag=True, help='check that longitude and latitude are in defined ranges. Configure list of accepted values in config.py')
@click.option('-v', 'verbose', is_flag=True, help='enable verbose output')
def cli(input_dir, output_dir, fix_coord_chars, fix_lon_lat, check_lon_lat, verbose):
  """This script converts institution.xml files to json v2 format.
  It requires positional parameters input_dir and output_dir.
  input_dir specifies the input directory with institution.xml files.
  output_dir specifies the output directory for json files.
  """

  main(input_dir, output_dir, { "fix_coord_chars" : fix_coord_chars, "fix_lon_lat" : fix_lon_lat,
                                "check_lon_lat" : check_lon_lat, "verbose" : verbose })

if __name__ == "__main__":
  cli()
```

I'm not getting just:
```bash
$ ./converter.py 
Usage: converter.py [OPTIONS] INPUT_DIR OUTPUT_DIR

Error: Missing argument "input_dir".
```

This is not acceptable for me. Also anyone using the script needs to run it explicitly with `--help` to view full help.

There is way to explicitly call help for defined command, composed together is looks like this:
```python
def print_help_msg(command):
  with click.Context(command) as ctx:
    click.echo(command.get_help(ctx))

  sys.exit(1)

# ==============================================================================
@click.command()
@click.argument('input_dir', type=click.Path(exists=True), default=print_help_msg(cli))
@click.argument('output_dir', type=click.Path(exists=True), default=print_help_msg(cli))
@click.option('-fc', 'fix_coord_chars', is_flag=True, help='fix wrong characters used in coordinates definitions')
@click.option('-fl', 'fix_lon_lat', is_flag=True, help='enable swapping of lon and lat if switched. Configure list of accepted values in config.py')
@click.option('-c', 'check_lon_lat', is_flag=True, help='check that longitude and latitude are in defined ranges. Configure list of accepted values in config.py')
@click.option('-v', 'verbose', is_flag=True, help='enable verbose output')
def cli(input_dir, output_dir, fix_coord_chars, fix_lon_lat, check_lon_lat, verbose):
  """This script converts institution.xml files to json v2 format.
  It requires positional parameters input_dir and output_dir.
  input_dir specifies the input directory with institution.xml files.
  output_dir specifies the output directory for json files.
  """

  main(input_dir, output_dir, { "fix_coord_chars" : fix_coord_chars, "fix_lon_lat" : fix_lon_lat,
                                "check_lon_lat" : check_lon_lat, "verbose" : verbose })

```

This code is unfortunately unusable because the function referenced in arguments does not exist yet.

I've managed to achieve the functionality i need, but the code is rubbish:
```python
@click.command()
@click.argument('input_dir', type=click.Path(exists=True))
@click.argument('output_dir', type=click.Path(exists=True))
@click.option('-fc', 'fix_coord_chars', is_flag=True, help='fix wrong characters used in coordinates definitions')
@click.option('-fl', 'fix_lon_lat', is_flag=True, help='enable swapping of lon and lat if switched. Configure list of accepted values in config.py')
@click.option('-c', 'check_lon_lat', is_flag=True, help='check that longitude and latitude are in defined ranges. Configure list of accepted values in config.py')
@click.option('-v', 'verbose', is_flag=True, help='enable verbose output')
def cli(input_dir, output_dir, fix_coord_chars, fix_lon_lat, check_lon_lat, verbose):
  """This script converts institution.xml files to json v2 format.
  It requires positional parameters input_dir and output_dir.
  input_dir specifies the input directory with institution.xml files.
  output_dir specifies the output directory for json files.
  """

  main(input_dir, output_dir, { "fix_coord_chars" : fix_coord_chars, "fix_lon_lat" : fix_lon_lat,
                                "check_lon_lat" : check_lon_lat, "verbose" : verbose })

# ==============================================================================
def print_help_msg(command):
  with click.Context(command) as ctx:
    click.echo(command.get_help(ctx))

  sys.exit(1)

# ==============================================================================
# duplicated here to define default for arguments
# ==============================================================================
@click.command()
@click.argument('input_dir', type=click.Path(exists=True), default=print_help_msg(cli))
@click.argument('output_dir', type=click.Path(exists=True), default=print_help_msg(cli))
@click.option('-fc', 'fix_coord_chars', is_flag=True, help='fix wrong characters used in coordinates definitions')
@click.option('-fl', 'fix_lon_lat', is_flag=True, help='enable swapping of lon and lat if switched. Configure list of accepted values in config.py')
@click.option('-c', 'check_lon_lat', is_flag=True, help='check that longitude and latitude are in defined ranges. Configure list of accepted values in config.py')
@click.option('-v', 'verbose', is_flag=True, help='enable verbose output')
def cli(input_dir, output_dir, fix_coord_chars, fix_lon_lat, check_lon_lat, verbose):
  """This script converts institution.xml files to json v2 format.
  It requires positional parameters input_dir and output_dir.
  input_dir specifies the input directory with institution.xml files.
  output_dir specifies the output directory for json files.
  """

  main(input_dir, output_dir, { "fix_coord_chars" : fix_coord_chars, "fix_lon_lat" : fix_lon_lat,
                                "check_lon_lat" : check_lon_lat, "verbose" : verbose })


if __name__ == "__main__":
  cli()

```

Can you please provide a clean way to solve this?

### PR DESCRIPTION
**Pull request by sirosen**
The functionality for no_args_is_help, available on MultiCommands, can easily be added on Commands as well. The result is not much more code, and a more consistent interface between MultiCommands and Commands.
It's also nice to be able to write a click command `foo` and then just hit `foo` for help, regardless of whether its a Group or Command.

closes #1156

Will add changelog edit in a moment, after this PR is assigned a number.

### CODE REVIEW

**Comment by sirosen** [comment]
I just had a coworker ask me about this feature (unaware of this PR), so I guess that's a 👍 from somewhere for this feature.

In #1156 I said I wasn't sure we needed this, but maybe I'm changing my tune on it. Seems easy for `click` to do, and confusing for people new to the framework.

**Comment by davidism** [comment]
Looks good to me.

Should there be a check that there is at least one required arg? Otherwise you wouldn't actually be able to run the command. Guess at that point you should have just not set `no_args_is_help` though.

**Comment by sirosen** [comment]
Yeah, I think "just don't try to do that" is a reasonable stance.
I wouldn't check for a required arg, since someone might have a command which takes a bunch of options which determine its behavior. e.g. `command --mode1` and `command --mode2` are valid, but `command` on its own is not.

I noticed a small typo in my changelog entry, which I just amended. That's why there's a fresh commit.

**Comment by simonkeng** [comment]
Hi, do developers need to wait for the 7.1 release to use this feature? Or is there a branch I can switch to in order to have access to this earlier? I'm using `Click==7.0` via `pip` but I would build it from the GitHub repo instead if I can access `no_args_is_help` without waiting for the 7.1 release. 

Thanks!

**Pull request merged**
