### PR TITLE
PR: a global ctx object

### LINKED ISSUE #292: A completely global ctx object
As discussed with @mitsuhiko in IRC, Click should support a global context object, for the same reason they're in Flask: Explicitly passing on the context object to utility functions is extremely verbose.

https://github.com/untitaker/vdirsyncer/blob/master/vdirsyncer/doubleclick.py implements this in some way. Note that unlike Flask, this object is not local to the current thread. That wouldn't make much sense for CLI tools anyway.

### PR DESCRIPTION
**Pull request by untitaker**
Fix #292

---
- [x] Use better exceptions, provide own ones
- [ ] Does bool behavior of `click.ctx` make sense? I personally liked it in [vdirsyncer's doubleclick wrapper](https://github.com/untitaker/vdirsyncer/blob/master/vdirsyncer/doubleclick.py), it was useful for checking whether ctx is available.
- [ ] Deprecate/remove `pass_context`?

### CODE REVIEW

**Comment by repole** [comment]
I'm not sure if this is intended/expected behavior, but spawning a child process and trying to check click.ctx fails:

```python
import click
import multiprocessing


def test():
    print(click.ctx.obj)


@click.command()
@click.argument("arg", nargs=-1)
def main(arg):
    """Some help text here."""
    click.ctx.obj = {"arg": arg}
    p = multiprocessing.Process(target=test)
    p.start()
    p.join()

if __name__ == '__main__':
    main()
```

Results in a nice traceback:
```
Process Process-1:
Traceback (most recent call last):
  File "C:\Python33\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python33\lib\multiprocessing\process.py", line 95, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Nick\Documents\Projects\clicktest\run.py", line 6, in test
    print(click.ctx.obj)
  File "C:\Users\Nick\Documents\Projects\clicktest\click\context.py", line 30, i
n <lambda>
    __getattr__ = lambda s, n: getattr(s._click_ctx_stack.top, n)
  File "C:\Users\Nick\Documents\Projects\clicktest\click\context.py", line 7, in
 top
    return self._stack[-1]
IndexError: list index out of range
```

**Comment by untitaker** [comment]
The traceback is not very nice (custom exceptions is already a subtask). I'm not sure if it's possible to support multiprocessing -- the whole ctx object and everything on it would have to be pickleable. I've philosophized about that in a related issue, can't link ATM (on mobile).

If it's a widely requested feature we could add it as an afterthought or even third-party pkg.

Threading, however, works perfectly fine... wouldn't this work out for you?

**Comment by repole** [comment]
Makes sense. My actual use case unfortunately requires processes (my main script delegates a number of sub processes based on command line input), threading would introduce a pretty big performance bottleneck for me.

Certainly understand it not being a priority, just figured it was worth bringing up. For now I'll work around it.

**Comment by untitaker** [comment]
#379.

**Pull request closed without merging**
