### PR TITLE
Extract bar formatting to own method

### PR DESCRIPTION
**Pull request by flying-sheep**
Enhances subclassability of ProgressBar. Related to #399

### CODE REVIEW

**Comment by untitaker** [comment]
I'd really like to hear Armin's opinion about exposing that class.

On 27 August 2015 10:37:05 CEST, "Philipp A." <notifications@github.com> wrote:
>Enhances subclassability of ProgressBar. Related to #399
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/mitsuhiko/click/pull/414
>
>-- Commit Summary --
>
>  * Extracted bar formatting to own method
>
>-- File Changes --
>
>    M click/_termui_impl.py (32)
>
>-- Patch Links --
>
>https://github.com/mitsuhiko/click/pull/414.patch
>https://github.com/mitsuhiko/click/pull/414.diff
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/pull/414

-- 
Sent from my phone. Please excuse my brevity.

**Comment by flying-sheep** [comment]
@mitsuhiko what do you think?

**Comment by flying-sheep** [comment]
boink

**Comment by mitsuhiko** [comment]
I honestly am not sure.  I think the progressbar needs love but the class is too complex for me to consider exposing currently.

**Comment by flying-sheep** [comment]
we should take lections from [progressive](https://pypi.python.org/pypi/progressive/0.3.0).

simply nesting `with progressbar(...) as outer_bar: ...` calls should be possible

**Comment by dsully** [comment]
Going to pull this in. Re-doing the progressbar might happen at some point in the future.

**Pull request merged**
