### PR TITLE
proposal of more modern tox.ini and .travis.yml styles

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this one is for consideration, it implements smarter matrix builds and uses more modern tox features
it also replaces the makefile

### CODE REVIEW

**Comment by untitaker** [comment]
Unsure about replacing Makefile with language-specific tox.

Perhaps Makefile could be a wrapper for tox?

**Comment by RonnyPfannschmidt** [comment]
Its a python only project to begin with and tox is more portable

**Comment by amcgregor** [comment]
T'was exploring and ran across this pull.  Interestingly, in my own packages I have recently stripped out all things Tox entirely, as Travis already provides Python language matrix options.  Previously using `tox-travis` to translate that through, but then I realized I didn't need to create a new venv within my existing venv (adding more than 700 files) just to run `setup.py register sdist bdist_wheel upload`, plus that Tox utterly broke for a while making my tests undiscoverable.

On the regenerating documentation front, Make has built-in change tracking and dependency collection.  I.e. it's smart enough to not regenerate docs unless needed, or, [not re-run `setup.py develop` unless the metadata has actually changed](https://github.com/marrow/cinje/blob/develop/Makefile#L27), etc.  It's the mature build system that Tox is not.  (In a similar way that Tox is the test isolation framework that Make is not.)  As a developer dependency, Make is universal.

**Comment by RonnyPfannschmidt** [comment]
@amcgregor well, how do i as a developer run a travis matrix locally - thats the mian point of tox - local execution so i can test my changes locally, directly without the internet

while i am not exactly happy with the tox syntax either, its still completely beating any other tooling i have seen for that

also its not just about python versions, but also about matrices with dependencies/versions of dependencies

my experience with make is pretty much, that it is not up to par even remotely as soon as a matrix comes into play

**Comment by untitaker** [comment]
Abandoning tox was never up for debate.

**Comment by amcgregor** [comment]
> Abandoning tox was never up for debate.

I'm very sorry people stopped reading at the anecdote.

I'm against the idea of this pull request to force Tox to do things it was not meant to do in the name of purity or out of some distaste of make simply because it's a technology that is older than a bulk of developers in the industry.  To quote:

> It's the mature build system that Tox is not. (In a similar way that Tox is the test isolation framework that Make is not.)

Use the right tool for the right job, is all.  The majority of your reply @RonnyPfannschmidt, seems based on the presumption that I'm suggesting removal of Tox. Which I am not.

```
[testenv:upload-docs]
...

[testenv:release]
...
```

Those are pinned environments pretending to be phony Make targets, not build matrix ones, so I really don't grok:

> its not just about python versions, but also about matrices with dependencies/versions of dependencies

When clearly, the _automation_ part has nothing to do with matrices.  Or dependencies.  Or versions of dependencies.  Excluding the cases where it actually could, _if using Make_.  (E.g. dependent metadata rebuilding, documentation rebuilding only if source files were updated, etc.)

**Comment by untitaker** [comment]
Thanks for making your point clear (I agree).

>I'm very sorry people stopped reading at the anecdote.

You didn't specify your concrete suggestion at all and instead aimed at what seemed like a direct comparison between make and tox, so I was left to guess. Implying that people are too lazy to understand a point you initially didn't make is rude.

**Comment by RonnyPfannschmidt** [comment]
@amcgregor i see what you mean, now - tox is indeed not meant for that automation, but does it already more portable than make (hello windows)

i actually plan to add this to tox in a more complete manner (for stuff like linters its also very sensible)

**Comment by amcgregor** [comment]
http://gnuwin32.sourceforge.net/packages/make.htm — same version that came bundled with Xcode.   One problem solved after a two second Google search.

Tox and Make automation are "developers of the library" tools, not "users of the library" tools, i.e. needed to work on Pallets, but not use Pallets.  This makes such strict removal of non-Python dependency silly, as the target audience that would benefit from it is minuscule, and should actually already have a better environment (with proper tooling) set up anyway.  There's also the fact that of the two phony make targets, upload-docs and release, neither are for general use.  Only for use by maintainers of the package, an even smaller target demographic.

Then there's the whole "creating a venv even when one is not necessary" aspect.  After invoking those two tox commands you'll end up with more than 1500 files across two venvs. The inefficiency and waste people find acceptable in the name of purity I just don't comprehend.  All of that construction and maintenance time, and disk space (which, in my case, is actually cloud-backed storage, so every file that changes represents an upload) adds up.

On the linting front, a little `pytest-flakes` goes a long way, especially when combined with [`pre-commit`](http://pre-commit.com) ([example config](https://github.com/marrow/cinje/blob/develop/.pre-commit-config.yaml)).  (And yes, it's Python. ;)

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell you propose a less automated setup that a developer manually has to set up to get to work ^^ including lots of local plugins/modifications that affect results

personally i never ever want to deal with projects making such a setup the only option,
in my prior experiences that made "works for me" easy and "works for everyone" hard

and i do projects broad consumption, so every step that someone could mess up i want to see automated and easy to take on with the least amount of initial tooling, googling and hand-installing

as such, the combination of tools you propose really just do not fit that philosophy off-hand
and this discussion is starting to derail the actual pr

**Comment by amcgregor** [comment]
> including lots of local plugins/modifications that affect results

~~Wat?~~  Actually, I don't want to know.  If you see _that_ in a two-target Makefile, with no "plugins" or "modification", used only by maintainers, I don't know what I can say.

**Comment by davidism** [comment]
Closing this not for any of the things that @amcgregor decided to say, but because I want to unify this with the configs from Flask. I'm still not 100% comfortable with Travis doing deploys, but maybe we'll get there eventually.

**Pull request closed without merging**
