### PR TITLE
Create contributing.rst

### PR DESCRIPTION
**Pull request by Yourun-proger**
Hello! I noticed that there is a contributing page in the flask documentation. It is not in click docs, so I decided to add this file.

### CODE REVIEW

**Comment by Yourun-proger** [comment]
hm.. 
**WARNING: document isn't included in any toctree**
How i can fix it?

**Comment by davidism** [comment]
Thanks, I'm planning on a different thing for this going forward, so I don't want to add this page to any of the other docs right now.

**Comment by Yourun-proger** [comment]
Hello, @davidism! It sounds great) I was thinking about one more thing. Do you think it is necessary to change the part about venv activation to the same as described in flask?

**Comment by davidism** [comment]
As a reminder, reposting my previous response to you from another PR:

> I appreciate that you are interested in contributing, but the docs changes you've made so far have generally not been successful and it's becoming too much for me to evaluate and respond to each one. Going forward, please contribute substantial fixes to existing code-related issues only. Identifying unreported issues and working on docs has not been successful for you.

**Comment by Yourun-proger** [comment]
okay) i'll never do it again . Let the professionals think

**Pull request closed without merging**
