### PR TITLE
Remove "Work in progress caveat"

### PR DESCRIPTION
**Pull request by gambogi**
As per #394.

### CODE REVIEW

**Comment by untitaker** [comment]
I think that last sentence is awkward on its own.

**Comment by davidism** [comment]
I really don't see the problem with the original wording, but maybe just change it to "stable and active" rather than "in progress".  "This library is stable and actively developed.  Feedback is encouraged and appreciated!"

**Comment by pradyunsg** [comment]
I was thinking something along the lines of:

```diff
- This library is a work in progress.  Please give feedback!
+ This library is stable and actively developed. Any feedback and help will be greatly appreciated!
```

But something like that @davidism would do the job equally well. (I like this one better)

```diff
- This library is a work in progress.  Please give feedback!
+ This library is stable and actively developed. Feedback is always appreciated!
```

**Comment by mitsuhiko** [comment]
I can live with this :)

**Pull request merged**
