### PR TITLE
Add the ability to hide commands and options from help

### PR DESCRIPTION
**Pull request by mattrobenolt**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
@mattrobenolt can you add a CHANGES entry?

**Comment by mattrobenolt** [comment]
Yup, would you like something in docs too? I couldn't think of where you'd want it.

**Comment by mitsuhiko** [comment]
@mattrobenolt i think it's fine for now as it's pulled into the api docs anyways. I will try to remember it when i land the help changes.

**Comment by galgalesh** [comment]
Hi

Which click version will this be included in?


Kind regards
Merlijn

**Comment by stuaxo** [comment]
Hi
 @mitsuhiko any chance of a new release on pypi with this functionality ?

S

**Comment by jsmedmar** [comment]
I tried upgrading to 6.6, but it seems not to be included yet.

**Comment by untitaker** [comment]
This will be included in 7.0

**Comment by annakz** [comment]
Is there any prognosis when 7.0 version will be released?

**Comment by wfdd** [comment]
Thanks for adding this, but it's been a year and a half now since then - any chance it can be backported if 7.0 is not forthcoming?

**Comment by AlmogCohen** [comment]
Agree with the guy above ^^

**Comment by wreed4** [comment]
Please release this?

**Comment by luisdavim** [comment]
so, is 7.0 coming out anytime soon or will this be back ported to 6.x?

**Comment by sstaszkiewicz-copperleaf** [comment]
Almost 2 years since merged amigos. Maybe we need a PR to backport it?

**Comment by wreed4** [comment]
@untitaker Some motion on releasing this would be awesome.

**Comment by sstaszkiewicz-copperleaf** [comment]
Took at a stab at it in #985

**Comment by AlanCoding** [comment]
I also have an open issue in a project that is waiting for this release, over at https://github.com/ansible/tower-cli/issues/337

**Pull request merged**
