### PR TITLE
Improve Travis / tox setup + coverage

### PR DESCRIPTION
**Pull request by blueyed**
Mainly inspired by using pytest directly in tox, for easy test selection
etc.

### CODE REVIEW

**Comment by blueyed** [comment]
Added coverage reports via codecov, which can be seen at https://codecov.io/gh/pallets/click/pull/851/tree.

**Comment by blueyed** [comment]
@untitaker @axu2 
Can you take a look, please?

**Comment by blueyed** [comment]
Also please authorize/install codecov on https://codecov.io/gh/pallets/click/.

**Comment by untitaker** [comment]
I wouldn't include codecov, particularly its notification settings are
extremely buggy in my experience. I feel like it's more maintenance effort than
it brings insight

**Comment by blueyed** [comment]
@untitaker 
What do you mean by "extremely buggy"?
What I am seeing sometimes is multiple comments, also only one should be there and edited.

> maintenance effort

Do you mean that you have or want to delete the duplicated comments then?

If this is the issue you mean it might be solvalble by @codecov just fixing it in the end.. ;)

From my point of view codecov provides a lot of valuable insights.

**Comment by ThiefMaster** [comment]
IMO even just a single codecov comment on every PR is somewhat annoying. I like getting notifications from GitHub for new PRs and comments since that's convenient to see if there's anything to comment on, a PR to review, etc. But codecov comments? I'm tempted to overcome my laziness and configure my email filter to send the notifications about them straight to the trash folder. But that aside, IMO these comments are more noise than adding useful comment.

**Comment by blueyed** [comment]
@ThiefMaster 
The recommended way is to install codecov's GitHub integration, where you would not see comments in your emails (AFAIK): https://github.com/integration/codecov.
Anyone with admin rights here could try it already.

Otherwise you could also just block the bot user (https://github.com/codecov-io), and be done with it I guess.

**Comment by blueyed** [comment]
Especially for PRs codecov's reporting is valuable, since it will tell you if coverage drops and if the diff is covered etc.

**Comment by untitaker** [comment]
If codecov were about to "just fix" anything they would have done that a long time ago.

On 6 October 2017 21:38:40 GMT+02:00, Daniel Hahler <notifications@github.com> wrote:
>@untitaker 
>What do you mean by "extremely buggy"?
>What I am seeing sometimes is multiple comments, also only one should
>be there and edited.
>
>> maintenance effort
>
>Do you mean that you have or want to delete the duplicated comments
>then?
>
>If this is the issue you mean it might be solvalble by @codecov just
>fixing it in the end.. ;)
>
>>From my point of view codecov provides a lot of valuable insights.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/pull/851#issuecomment-334850731

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blueyed** [comment]
@untitaker 
It is still the best service for it, isn't it?  coveralls is much worse and there is no other.

**Comment by untitaker** [comment]
Hence my suggestion to not have any such service.

On 7 October 2017 00:09:43 GMT+02:00, Daniel Hahler <notifications@github.com> wrote:
>@untitaker 
>It is still the best service for it, isn't it?  coveralls is much worse
>and there is no other.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/pull/851#issuecomment-334882005

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blueyed** [comment]
What about the benefit to see if a PR covers its diff?

**Comment by blueyed** [comment]
And even in general, I think you can grasp a lot of useful info from https://codecov.io/gh/pallets/click/tree/improve-travis-tox/click already.

**Comment by untitaker** [comment]
I never disputed that the information provided by the service would be useful. But for that it would have to work properly, and that just has not been my experience at all. Flaky reports and/or random build failures because their weird CLI tool was unable to contact S3 or whatever.

Bot comments are a non-starter, way too spammy, 

On 7 October 2017 00:13:51 GMT+02:00, Daniel Hahler <notifications@github.com> wrote:
>And even in general, I think you can grasp a lot of useful info from
>https://codecov.io/gh/pallets/click/tree/improve-travis-tox/click
>already.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/pull/851#issuecomment-334882725

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
Ah, I see you used travis-retry for that purpose, fair enough.

I guess we can merge this and also immediately block the bot org-wide. That should do it.

On 7 October 2017 00:13:51 GMT+02:00, Daniel Hahler <notifications@github.com> wrote:
>And even in general, I think you can grasp a lot of useful info from
>https://codecov.io/gh/pallets/click/tree/improve-travis-tox/click
>already.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/pull/851#issuecomment-334882725

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blueyed** [comment]
@untitaker 
Thanks.

**Comment by blueyed** [comment]
btw: it might be better to use pytest-cov here, since it would also track subprocess automatically - not sure if that is used in tests?!

**Comment by untitaker** [comment]
Thanks! Codecov seems to be already activated.

**Pull request merged**
