### PR TITLE
Include --help option in completion

### PR DESCRIPTION
**Pull request by tiangolo**
Include `--help` option in completion.

When executing completion (in Bash, Zsh, etc) the `--help` option is currently omitted, even though it's available.

This allows the `--help` option to show up in completion if it was enabled.

This is the same way it's done in `click-completion`: https://github.com/click-contrib/click-completion/blob/master/click_completion/core.py#L92

### CODE REVIEW

**Comment by tiangolo** [comment]
I'm not sure where should I add the change in `CHANGES.rst`, above:

```
Version 7.1.1
-------------
```

without a version title?

Or should I create a dummy unreleased version title that you change later?

**Comment by ThiefMaster** [comment]
could you please omit the emoji in the commit messages? while they look pretty on GitHub, they are very noisy when reading the shortlog using the git CLI.

**Comment by davidism** [comment]
For the changelog, just start a new 7.2 section.

**Comment by tiangolo** [comment]
> could you please omit the emoji in the commit messages? while they look pretty on GitHub, they are very noisy when reading the shortlog using the git CLI.

@ThiefMaster sure thing. Just removed the hook. Changing the previous would mean force-pushing, so I won't do it, but I assume you squash and merge when/if you accept it so they won't end up in the history.

> For the changelog, just start a new 7.2 section.

@davidism perfect, done.

**Comment by tiangolo** [comment]
Thanks! :rocket: :tada:

**Pull request merged**
