### PR TITLE
Allow path_type of the Path type to accept a callable (`#405`_)

### LINKED ISSUE #405: click.Path returns str, not pathlib.Path
It’s surprising that `INT` returns an `int`, `File` a `file`, `STRING` a `str`, but `Path` a …`str`?

A `click.Path` parameter should return a `pathlib.Path` object.

### PR DESCRIPTION
**Pull request by termim**
This would allow to convert path names to pathlib.Path instances
for example.

closes #405

### CODE REVIEW

**Review by LucidOne — CHANGES_REQUESTED** [review]
I looks like [this assertion](https://github.com/pallets/click/pull/1234/files#diff-9de36928a31dc2292c5f42ea1a3afbb4R157) needs to be uncommented.

**Comment by LucidOne** [comment]
Ran `tox` on this locally
```
  py37: commands succeeded
SKIPPED:  py36: InterpreterNotFound: python3.6
  py35: commands succeeded
SKIPPED:  py34: InterpreterNotFound: python3.4
  py27: commands succeeded
SKIPPED:  pypy3: InterpreterNotFound: pypy3
SKIPPED:  pypy: InterpreterNotFound: pypy
```

I also tested this with an application I'm developing by adding `git+https://github.com/termim/click.git@I405#egg=click` to my `requirements.txt` and it works as advertised.

However, using `pathlib.Path` as the `path_type` with [Click7.0](https://github.com/pallets/click/commit/a936b99212c69a36a2cc2828252b2c4280c0c88c)
```
@click.option('--config', '-c', type=click.Path(exists=True,dir_okay=False,path_type=pathlib.Path), required=False, help='Config file')
```
sets `config` to type `bytes` though backwards compatibility can be maintained as needed with
```
config = pathlib.Path(config.decode()) if isinstance(config,bytes) else config
```
as `pathlib.Path(None)` isn't accepted.

Also, I'm not sure if there would be an advantage to setting [this](https://github.com/pallets/click/pull/1234/files#diff-9de36928a31dc2292c5f42ea1a3afbb4R141) to `isinstance(input,os.PathLike)` but it may be worth considering.

Aside from the above it looks good to me, I would like to see this merged.

**Comment by termim** [comment]
> I looks like [this assertion](https://github.com/pallets/click/pull/1234/files#diff-9de36928a31dc2292c5f42ea1a3afbb4R157) needs to be uncommented.

Done.

**Comment by termim** [comment]
> However, using `pathlib.Path` as the `path_type` with [Click7.0](https://github.com/pallets/click/commit/a936b99212c69a36a2cc2828252b2c4280c0c88c)
> 
> ```
> @click.option('--config', '-c', type=click.Path(exists=True,dir_okay=False,path_type=pathlib.Path), required=False, help='Config file')
> ```
> 
> sets `config` to type `bytes` though backwards compatibility can be maintained as needed with

I can't reproduce this:
```
click>$ python3 --version
Python 3.5.2
click>$ cat t.py
import click
import pathlib

@click.command()
@click.option('--config', '-c', type=click.Path(exists=True,dir_okay=False,path_type=pathlib.Path), required=False, help='Config file')
def hello(config):
    click.echo('Hello %s!' % type(config))

if __name__ == '__main__':
    hello()
click>$ 
click>$ PYTHONPATH=./click python3 ./t.py -c ./t.py
Hello <class 'pathlib.PosixPath'>!
click>$ 
```
> 
> ```
> config = pathlib.Path(config.decode()) if isinstance(config,bytes) else config
> ```
> 
> as `pathlib.Path(None)` isn't accepted.
> 
> Also, I'm not sure if there would be an advantage to setting [this](https://github.com/pallets/click/pull/1234/files#diff-9de36928a31dc2292c5f42ea1a3afbb4R141) to `isinstance(input,os.PathLike)` but it may be worth considering.
> 

That would make click require pathlib2 for python2 ...

**Comment by LucidOne** [comment]
> > However, using `pathlib.Path` as the `path_type` with [Click7.0](https://github.com/pallets/click/commit/a936b99212c69a36a2cc2828252b2c4280c0c88c)
> > ```
> > @click.option('--config', '-c', type=click.Path(exists=True,dir_okay=False,path_type=pathlib.Path), required=False, help='Config file')
> > ```
> > sets `config` to type `bytes` though backwards compatibility can be maintained as needed with
> 
> I can't reproduce this:
> 
> ```
> click>$ python3 --version
> Python 3.5.2
> click>$ grep __version__ ./click/click/__init__.py 
> __version__ = '7.1.dev'
> click>$ cat t.py
> import click
> import pathlib
> 
> @click.command()
> @click.option('--config', '-c', type=click.Path(exists=True,dir_okay=False,path_type=pathlib.Path), required=False, help='Config file')
> def hello(config):
>     click.echo('Hello %s!' % type(config))
> 
> if __name__ == '__main__':
>     hello()
> click>$ 
> click>$ PYTHONPATH=./click python3 ./t.py -c ./t.py
> Hello <class 'pathlib.PosixPath'>!
> click>$ 
> ```

I was getting `bytes` using `path_type=pathlib.Path` without your PR on version 7.0.

**Comment by termim** [comment]
> I was getting `bytes` using `path_type=pathlib.Path` without your PR on version 7.0.

Ah, yes, without this #1234 it always returns bytes if path_type is not a string ...

**Comment by LucidOne** [comment]
`config = pathlib.Path(config.decode()) if isinstance(config,bytes) else config`
provides backwards compatibility, so application developers can move to `pathlib` while waiting for your PR to make it downstream.

**Pull request closed without merging**
