### PR TITLE
Included click.DateTime type (with tests)

### PR DESCRIPTION
**Pull request by santiagobasulto**
Anyone interested in something like this?

``` python
@click.command()
@click.option('--start_date', type=click.DateTime())
def cli(start_date):
    pass
```

You can always specify the formats you expect.

``` python
@click.command()
@click.option('--start_date', type=click.DateTime(formats=['%A %B %d, %Y']))
def cli(start_date):
    pass
```

### CODE REVIEW

**Comment by Riprock** [comment]
I came to ask about interest in essentially the same thing, which I have my own version for. Obviously unnecessary if this is merged.

I noticed in !44 that there was hesitation about including date types. If that's still the case then I'll go ahead and put something on pypi separately.

**Comment by pmdarrow** [comment]
I'm definitely interested in seeing this merged. Wondering what @mitsuhiko's thoughts are.

**Comment by dsully** [comment]
We can get this merged, but the PR needs some documentation added. Thanks for the tests!

**Comment by santiagobasulto** [comment]
@dsully I had forgotten about this one 😁 . I'll take a look at it in the morning.

**Pull request closed without merging**
