### PR TITLE
Enhancements to bash completions for better file/directory handling (take 2)

### PR DESCRIPTION
**Pull request by gtristan**
This addresses the issues outlined in #780 

* Changes the bash entry point to use *"complete -o nospace"*
* Adds abstract method to ParamType allowing the parameters to participate in the completion
* Migrates Choice completion implementation into types.py on the actual Choice type
* Implement the `completions()` method for BoolParamType, File and Path parameter types too

This behaves all around much better:
* No more completing of filenames when that is undesirable
* Completes filenames or directories selectively, depending on the parameter

**Note**: This is take two of pull request #781 ... I rebased my branch to have a more coherent history and did not expect github to delete the PR as a result, sorry.

### CODE REVIEW

**Comment by gtristan** [comment]
Addressed some corner cases regarding path name completions in some follow up commits instead of squashing those and rebasing the branch, as that seems to cause a merge request to be automatically closed.

I can rebase the branch locally so that these changes are squashed into the one commit implementing completions for file & directory paths, if that is desirable.

**Comment by davidism** [comment]
Completion has changed significantly since this PR was posted. Would you or @stopthatcow review this to see if it's still needed and can be rebased?

**Comment by stopthatcow** [comment]
There are definitely some attractive aspects of this PR. I like the idea of delegating some completion to the type. I can look into rebasing it on top of master this weekend.

**Comment by gtristan** [comment]
> There are definitely some attractive aspects of this PR. I like the idea of delegating some completion to the type, and path completion would be very nice to have. I can look into rebasing it on top of master this weekend, unless of course @gtristan wants to take a stab at it himself!

It's great to see some activity on this front !

I would certainly love to upstream this stuff, as we're doing some [pretty ugly hacks](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/_frontend/cli.py#L165) which [reimplement the completions](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/_frontend/complete.py) mechanism in order to get these features in BuildStream.

The most important part for us is the ability to perform *partial completions*, since we do completions of filenames which are intentionally not in the `CWD`, and soon we will be doing completions of entity names within a database/cache, these entities are also *"pathy"*. If partial completions are not supported, then it is rather unacceptably slow (one would need to recursively list every leaf in an unpredictably large tree in order to report a full completion list in one go; for every `<TAB>`).

As far as I know, this can only be done by enabling `-o nospace` in the bash completion script; so that the program handling completions has the decision to append a space (fully complete) or not (partially complete, next `<TAB>` will show deeper results).

I'll have to refresh my memory on how compatible my proposed changes were, but I'm pretty confident that by delegating completions to the type and to delegated user functions; we can make sure that the behavior of allowing partial completions is *opt in*.

**Comment by jsmedmar** [comment]
@gtristan Kudos to great work! Hope you can figure out this last bit so that we can see file completions in master. Again thanks so much for such thoughtful work in #780 and here.

**Comment by davidism** [comment]
@gtristan thanks for working on this. I'm going to close it in favor of the updated work in #1403.

**Comment by gtristan** [comment]
@davidism Thanks for reviewing and for everyone who picked up my abandoned patches :)

I will try to find time to upgrade click in BuildStream and drop our custom code in favor of this :)

**Pull request closed without merging**
