### PR TITLE
Help shown via no_args_is_help results in exit code 2, was 0

### LINKED ISSUE #1394: Command w/o args displaying usage should return non-zero
Try running `git`, and you will see its usage. You will also receive a non-zero return code, indicating failure. This can be vital in case arguments got truncated.

Current behavior of showing usage instructions (`help_text`) is great!

But it should also error out with a code `1`.

Example:

```
➜  git
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

(snip)

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
➜  echo $?
1
```

Reference: https://github.com/learningequality/kolibri/pull/5937

### LINKED ISSUE #1486: Not specifying a group's command exits with code 0
When a group is created with multiple commands, but the script is called without any commands, the exit code is 0. It looks like [this line](https://github.com/pallets/click/blob/466d0add86f48502db9c02c32e30287d39ab866b/click/core.py#L1028) just needs to be changed to have an exit code. But it's not clear if `ctx.fail()` should be used instead.

### Example Code

```python
import click

@click.group()
def cli():
    print("in group")

@cli.command()
def foo():
    print("foo")

@cli.command()
def bar():
    print("bar")

if __name__ == "__main__":
    print("before group")
    cli()
```

### Expected Behavior

A non-zero exit code.

### Actual Behavior

```shell
$ python click_poc.py 
before group
Usage: click_poc.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  bar
  foo
$ echo $?
0
```

### Environment

* Python version: Python 3.8.0
* Click version: Click==7.0

### PR DESCRIPTION
**Pull request by fdavis**
fixes #1394
fixes #1486

### CODE REVIEW

**Comment by davidism** [comment]
`Command` can also have `no_args_is_help`. I think the error code should be 2 instead of 1 to match other usage errors.

**Comment by davidism** [comment]
Changing this caused a test to fail, but it seems to be revealing something weird about the processing, not a problem with this change. The following causes an exit code of `2`, even though `--help` was passed so it should result in `0`.

```python
import click

@click.group()
@click.argument("obj")
def cli(obj):
    click.echo(f"obj={obj}")

@cli.command()
def move():
    click.echo("move")

cli(["obj1", "--help"])
```

The problem is caused here in `MultiCommand.resolve_command`: https://github.com/pallets/click/blob/0ad4e7985a919041ec590a4d672afb44f05dd162/src/click/core.py#L1398-L1407

`ctx.args` is empty at this point, which causes the `no_args_is_help` behavior. Since that matched the actual `--help` behavior before, the issue wasn't caught. Seems like it might be related to #473.

**Comment by davidism** [comment]
Ironically, I just closed #1323 which discussed how the processing pipeline needs a rewrite, and then re-discovered that this PR demonstrates the issue.

**Comment by davidism** [comment]
Pushed a new implementation that uses a new `NoArgsIsHelpError` to match how other usage messages are handled. This doesn't fix the processing issue.

**Comment by davidism** [comment]
I started looking into this before 8.1, and it's too complex to disentangle the pipeline issues right now.

**Comment by benjaoming** [comment]
Nice one @AndreasBackx :raised_hands:

**Pull request merged**
