### PR TITLE
Draw attention to an easy mistake to make

### PR DESCRIPTION
**Pull request by Alphare**
Hi.

I just spent 10 minutes trying to figure out why my very simple code would not work, and this change would have helped me a lot. :smiley: 

There is an explanation in the "Nesting commands" section, but if you - like me - tried directly going for the "Commands" section, you might have ran into the same issue I did.

 Thanks for `click`, it's awesome!

### CODE REVIEW

**Comment by ThiefMaster** [comment]
You need to rebase this PR against 7.x or change it to master - currently it tries to merge all the stuff from master into 7.x.

**Comment by davidism** [comment]
From your branch you *should* be able to do `git rebase --onto 7.x master` to fix this. After that `git log` should show that it's close to the 7.x branch, then you can do `git push -f` to update the PR.

**Comment by davidism** [comment]
Rebased onto 7.x.

**Comment by Alphare** [comment]
@davidism Thanks, I tried doing so as soon as I opened the PR and saw the other commits, but you were faster.

**Pull request merged**
