### PR TITLE
Use sphinx theme from separate repo

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I'm quite happy with just not supporting a custom theme at all in the repo.  That's what we're doing with Sentry now and it works good enough.

**Comment by mitsuhiko** [comment]
I set the theme to the implied default in the `conf.py` that's in master right now.

**Comment by untitaker** [comment]
I'm not happy with it :) As said, personal motivation is RTD, but it's IMO also a good idea to separate the theme from the build system we have. Ideally I'd like to be able to replicate the exact docs (minus the version switcher) locally.

**Comment by untitaker** [comment]
If you feel it's important to leave the logo out, perhaps that's something the doc builder could patch on top, or we enable/disable it with an envvar.

To reiterate, I find RTD's build process much more "transparent" (for lack of a better word).

**Comment by untitaker** [comment]
If you're fine with it I'll merge this and modify flask-docs to use the same conf.py @mitsuhiko

**Comment by mitsuhiko** [comment]
I'm happy to pay for a heroku app if you are not happy with the current builder.

**Comment by untitaker** [comment]
That's not a problem, and I'm fine with SSH access. I still believe that the build process should be more standardized. Currently flask-docs seems to clone the repo and overwrite the conf.py, which is not obvious to one who tries to build the docs and expects them to resemble the online ones.

**Comment by mitsuhiko** [comment]
As far as I am concerned, the local docs are not a feature I need to have supported.

**Comment by untitaker** [comment]
FWIW that would be the solution to the issue of keeping the theme in sync on RTD that's been bothering you @mitsuhiko 

However, if you change the theme you'd need to trigger a build manually (which is just pushing a button in the admin interface)

**Comment by JosiahDub** [comment]
This PR no longer seems relevant.

**Pull request closed without merging**
