### PR TITLE
Replace newlines with spaces in multiline help

### LINKED ISSUE #834: Option format text should replace newlines with spaces
In Mailman 3, we write options like so:

```python
@click.option(
    '-C', '--config', 'config_file',
    envvar='MAILMAN_CONFIG_FILE',
    type=click.Path(exists=True, dir_okay=False, resolve_path=True),
    help=_("""\
    Configuration file to use.  If not given, the environment variable
    MAILMAN_CONFIG_FILE is consulted and used if set.  If neither are given, a
    default configuration file is loaded."""))
```
This makes it possible to translate the help text, but because the source formatting is a triple quoted string, there are embedded newlines in the help text.  We have to preserve the original source string text so that it can be looked up in the i18n catalog, and we can't really change the `_()` function to strip newlines at runtime because the source strings are extracted by an offline process that does not execute the source code.

After some pdb tracing, I've noticed that click already dedents the help text, which is great, but it *also* needs to substitute spaces for newlines, otherwise the wrapping of the help text isn't correct.  For example, the above by default gets printed on the console like so:

```
$ mailman --help
...
Options:
  -C, --config PATH  Configuration file to use.  If not given, the
                     environment variable
                     MAILMAN_CONFIG_FILE is consulted
                     and used if set.  If neither are given, a
                     default
                     configuration file is loaded.
```
Here's a small change that makes the `-C` option print correctly:

```python
    def format_options(self, ctx, formatter):
        """Writes all the options into the formatter if they exist."""
        opts = []
        for param in self.get_params(ctx):
            rv = param.get_help_record(ctx)
            if rv is not None:
                part_a, part_b = rv
                opts.append((part_a, part_b.replace('\n', ' ')))

        if opts:
            with formatter.section('Options'):
                formatter.write_dl(opts)
```

and now:

```
$ mailman --help
...
Options:
  -C, --config PATH  Configuration file to use.  If not given, the
                     environment variable MAILMAN_CONFIG_FILE is consulted
                     and used if set.  If neither are given, a default
                     configuration file is loaded.
```

Much better!

### PR DESCRIPTION
**Pull request by warsaw**
Closes #834

### CODE REVIEW

**Comment by sirosen** [comment]
The related change I see is #1081 , which isn't quite the same case.

Looking at this, what do we think of having `HelpFormatter.write_dl` preprocess the help text as follows?
(Version below is kind of hacked up, I'll try to come up with something smoother/tidier if the general idea gets a 👍.)

```python
# split on newlines
lines = helptext.split('\n')
# remove any leading or trailing spaces
lines = [l.strip() for l in lines]
# remove any trailing newline
if lines[-1] == '':
    lines = lines[:-1]
# recreate newlines -- with `split`, effectively recreates all but one newline
# so, `\n\n` becomes `\n` , `\n\n\n` becomes `\n\n` , etc
for i in range(len(lines)):
    if lines[i] == '':
        lines[i] = '\n'
    # if there are two non-newline lines in a row, add a trailing space to separate them
    elif i + 1 < len(lines) and lines[i + 1] != '':
        lines[i] += ' '
# rejoin, relying on the spacing work above
helptext = ''.join(lines)
```

trying this out on
```text
hello
i am not
multiline

but also sometimes


multiline
```

I see output of

```text
hello i am not multiline
but also sometimes

multiline
```

which seems about like what someone writing help text would expect/hope to see?
And then the results can be fed to the line-wrapping code.

That covers the case in #834 of a multiline string with no spacing and also doesn't break existing usage with newlines for separate paragraphs in a surprising way.
I can work up a new PR to replace this one if it seems appealing.

**Comment by davidism** [comment]
Whoops, looks like #1406 was this but rebased onto 7.x, instead of rebasing this PR. Closing as the other one is merged.

**Comment by davidism** [comment]
I think we do need something that allows newlines though, see #1066, #1307, #1397, etc.

**Comment by davidism** [comment]
Turns out the underlying `wrap_text` function already takes a `preserve_paragraphs` option, but it's not enabled for option help text right now. This enables the behavior in the command help text where `\n\n` is preserved and each paragraph is wrapped separately.

**Pull request closed without merging**
