### PR TITLE
Unicode issues in Python 2

### PR DESCRIPTION
**Pull request by bmcorser**
When using unicode literals in Python 2, it's possible (and not that hard) to make Click bomb out when it raises an exception. Below are failing and succeeding builds. There's probably a more general test case.

Failing case: https://travis-ci.org/bmcorser/click/builds/61146119
Fix: https://travis-ci.org/bmcorser/click/builds/61146510

### CODE REVIEW

**Comment by untitaker** [comment]
Hello @bmcorser, thanks for this patch!

* Please don't create a separate file for your testcase -- the same test can be implemented without the `__future__` import, using `u"..."`-literals instead.
* Your fix is broken -- it checks whether the string is NOT unicode (i.e. bytestring), then calls `encode` on it. You want the opposite check -- in your testcase, `message` is initially a unicode string, but you want to convert it into a `str`, which means bytestrings on Python 2 and unicode on Python 3.
* Funnily enough, just doing that fails too:

        def format_message(self):
            if self.param_hint is not None:
                param_hint = self.param_hint
            elif self.param is not None:
                param_hint = self.param.opts or [self.param.human_readable_name]
            else:
                return 'Invalid value: %s' % self.message
            if isinstance(param_hint, (tuple, list)):
                param_hint = ' / '.join('"%s"' % x for x in param_hint)
    >       return 'Invalid value for %s: %s' % (param_hint, self.message)
    E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)

  But this is another bug. `param_hint` seems to be unicode on Python 2, while it shouldn't be.

**Comment by bmcorser** [comment]
I think my test didn't reproduce actual error I encountered. Shall I close this PR and just make an issue?

**Comment by untitaker** [comment]
Feel free to make an issue, but we still need to be able to reproduce your issue.

**Comment by mitsuhiko** [comment]
Unicode literals is not supported.  Please use `u''` and `b''` to support unicode on 2.x and 3x.

**Pull request closed without merging**
