### PR TITLE
Add Float Range in Types

### PR DESCRIPTION
**Pull request by DenisCarriere**
When using the `IntRange` type I assumed that a similar `FloatRange` would exist.

### CODE REVIEW

**Comment by untitaker** [comment]
Excellent, could you add a changelog entry? Thanks!

**Comment by DenisCarriere** [comment]
@untitaker submitted another PR for the changelog entry

**Comment by untitaker** [comment]
No, please make the change on the same branch, in the same PR

On 4 April 2016 20:42:19 CEST, Denis <notifications@github.com> wrote:
>@untitaker submitted another PR for the changelog entry
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/pull/538#issuecomment-205442308

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DenisCarriere** [comment]
Sounds good, I'm still new to Git, I've re-submitted a commit to this PR now.
@untitaker

**Comment by untitaker** [comment]
Excellent, thanks!

**Comment by pokey** [comment]
@untitaker this doesn't seem to be in the pip package yet, and isn't documented on the website, even though the latest release was more than 8 months after this change merged.  Any idea why that would be the case?  Thank you

**Comment by untitaker** [comment]
It's because the release you're referring to was a bugfix release, not a major
one.

New features are only added as part of a major release, and the last major
release was 6.0.

**Pull request merged**
