### PR TITLE
update link

### PR DESCRIPTION
**Pull request by Yourun-proger**
There is already a new stable version of the documentation.

### CODE REVIEW

**Comment by greyli** [comment]
If we need to update this link, it's better to use `https://click.palletsprojects.com/setuptools/` so that we don't need to update it in the future.

**Comment by Yourun-proger** [comment]
@greyli , yes. This is realy better)

**Comment by Yourun-proger** [comment]
Will you accept this or should I close this PR?

**Comment by davidism** [comment]
Please don't ask when we'll merge things, well get to it as we have time.

**Pull request merged**
