### PR TITLE
Expand unit testing around termui (getchar testing for Windows)

### PR DESCRIPTION
**Pull request by icreatedanaccount**
#1116

### CODE REVIEW

**Comment by sirosen** [comment]
Sorry it took me so long to look through this (even after [I said I would](https://github.com/pallets/click/issues/1116#issuecomment-491396566))!

This looks really good. I can't think of a better way of testing getchar. 👍 

I have a vague worry that these tests could turn out to be flaky or hard to maintain over the long term, but _if_ they do we can mark skip or remove. That's not a reason to block and wait.

I want to add a time limit to these tests so that if something changes and the tests hang and wait for input, pytest will abort. But I'll open that up as follow-up work and we can discuss there.

I'm going to retarget this to `7.x-maintenance` instead of `master`, on the grounds that we want to test future 7.x releases with this. And I'll resolve any changelog conflict in a rebase-merge, since it's by my doing -- slow review -- that conflicts may have arisen.

**Review by sirosen — APPROVED** [review]

**Comment by davidism** [comment]
I recently added pytest-timeout to a test, it was really straightforward.

**Comment by sirosen** [comment]
Yeah, I didn't want to fold that in here because it doesn't look like `click` currently has `pytest-timeout` in the dependencies. So it means some tox.ini editing, etc. It should be easy to add though.

**Comment by davidism** [comment]
@sirosen would you be able to create a ticket for adding these things? I'm running a sprint next week and it sounds like a good task for someone to work on.

**Comment by sirosen** [comment]
Sorry I didn't get to this faster -- I was off-grid a bit the past few days.
@davidism, I just opened https://github.com/pallets/click/issues/1326 and marked it `save-for-sprint`. I hope it's in time to be useful, but worst-case it's written up now.

**Pull request merged**
