### PR TITLE
Fix default values of multiple options with optional values

### LINKED ISSUE #2001: Can't set the default value for multiple options with optional values
The following example combines [optional values](https://click.palletsprojects.com/en/8.0.x/options/#optional-value) with [multiple options](https://click.palletsprojects.com/en/8.0.x/options/#multiple-options):

```python
#!/usr/bin/env python3

import click


@click.command()
@click.option('--label', multiple=True, is_flag=False, flag_value='default')
def cli(label):
    print(label)
    print(f"click.core._flag_needs_value: {click.core._flag_needs_value}")


cli()
```

```
$ ./test.py --label --label test
('<object object at 0x7f5ef63ec250>', 'test')
click.core._flag_needs_value: <object object at 0x7f5ef63ec250>
```

Expected result: `('default', 'test')`

Looks like when `multiple=True`, the sentinel value (`click.core._flag_needs_value`) is never substituted with the default value specified by `flag_value`.

Environment:

- Python version: 3.7.3
- Click version: 8.0.1

### PR DESCRIPTION
**Pull request by ikapelyukhin**
Fixes default values for multiple options with optional values. The sentinel object (`click.core._flag_needs_value`) is now properly replaced by the value of `flag_value`.

- fixes #2001

Checklist:

- [x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [x] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [x] Run `pre-commit` hooks and fix any issues.
- [x] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by ikapelyukhin** [comment]
Things get a bit weird with `ParameterSource` and multiple options: you might get some of the option values from defaults or the prompt, others specified explicitly on the command line.

Also, default values populated from `flag_value` have `ParameterSource.COMMANDLINE` rather than `ParameterSource.DEFAULT`, which doesn't seem right.

**Comment by davidism** [comment]
> Things get a bit weird with ParameterSource and multiple options: you might get some of the option values from defaults or the prompt, others specified explicitly on the command line.

That needs to be addressed, the value may only come from one source.

**Comment by ikapelyukhin** [comment]
> > Things get a bit weird with ParameterSource and multiple options: you might get some of the option values from defaults or the prompt, others specified explicitly on the command line.
> 
> That needs to be addressed, the value may only come from one source.

@davidism OK, I'll need some more input from you then, there are two potential cases that I'm seeing:

#### Without a prompt
```
@click.option('--foo', multiple=True, is_flag=False, flag_value='default')
```

So if you do `./script.py --foo --foo test` you'd get `('default', 'test')` as a value for `foo` option and the source is `ParameterSource.COMMANDLINE`, which is accurate for both items in the list because of how `flag_value` source is determined:

https://github.com/pallets/click/blob/ce152bd7215038f762ee918e6e181a5309ad57c9/src/click/core.py#L2867-L2869

So everything seems fine in this case as is, assuming that `ParameterSource.COMMANDLINE` is correct and shouldn't be `ParameterSource.DEFAULT` instead for one of the items.

#### With a prompt
```
@click.option('--foo', multiple=True, is_flag=False, flag_value='default', prompt="Foo")`
```

1) How do you even specify multiple values with a prompt? I'm getting an `Error: Value must be an iterable.` for whatever input I provide. Is prompting even supposed to work for options with `multiple=True`?

2) If I do `./script.py --foo --foo test`, am I expected to provide values via the prompt for both of them, or just the first one that's missing a value?

3) Provided that it is possible to use prompts with `multiple=True` and specify just one of the values, if I do `./script.py --foo --foo test` and specify one of the values after being prompted what's the `ParameterSource` then? One part of the value is coming from `ParameterSource.PROMPT` and the other one is coming from `ParameterSource.COMMANDLINE`.

Seeing how it doesn't seem possible to set an iterable value via the prompt, there's no problem with `ParameterSource` as is here either :sweat_smile:

**Comment by ikapelyukhin** [comment]
@davidism OK, I've reverted the changes related to prompting, as it's not really related to the issue at hand. So things should be pretty straightforward now and source is set to `ParameterSource.COMMANDLINE` whenever option's default value is being used.

**Pull request merged**
