### PR TITLE
added test and code

### PR DESCRIPTION
**Pull request by iluxame**
I've rebased https://github.com/pallets/click/pull/502
@jdell64 Thanks for the feature! We need this feature badly so I've rebased your PR. No worries, you are still the author of your code.
Feel free to rebase your code and submit it in the original PR.
In such case we will not need this PR

### CODE REVIEW

**Comment by iluxame** [comment]
@untitaker can you please take a look?

**Comment by untitaker** [comment]
@iluxame I have proposed a few alternatives in that thread which I consider better since they add no extra API, but haven't recieved any feedback.

**Comment by iluxame** [comment]
@untitaker Aha, sorry, somehow I missed it.
In my opinion its better to show help message with empty command.
in case of a sentence like "See command subcommand --help" user will need 2 commands instead of one. However from other point of view it will be clear to user that he didn't entered any meaningful input.

This patch actually aligns command user experience with group user experience. It seems that similar experience is less confusing. So I would prefer @jdell64 approach.

**Comment by iluxame** [comment]
@untitaker 
What do you think?

**Comment by davidism** [comment]
Decision made to keep current "see --help" message in #502.

**Pull request closed without merging**
