### PR TITLE
Have multiple Choice split env vars on comma

### PR DESCRIPTION
**Pull request by omribahumi**

### CODE REVIEW

**Comment by untitaker** [comment]
They're already split by space. Why do you want to change this?

**Comment by omribahumi** [comment]
@untitaker didn't know that.
Where is the code that does that? Couldn't find anything [in the documentation](http://click.pocoo.org/5/options/#choice-options)

**Comment by untitaker** [comment]
It's part of the doc for the variable you're overriding, see
`ParamType.envvar_list_splitter`.

**Comment by omribahumi** [comment]
Missed that. Thanks

**Pull request closed without merging**
