### PR TITLE
Don't claim empty stderrs weren't separately captured.

### PR DESCRIPTION
**Pull request by Julian**
Closes: #1193

### CODE REVIEW

**Comment by Julian** [comment]
Polite ping?

**Comment by kitchoi** [comment]
Today I ran into this same issue of not being able to assert that the STDERR is empty. :+1: for the change!

**Review by davidism — APPROVED** [review]

**Comment by davidism** [comment]
Needs to be rebased onto 7.x branch if you're adding the changelog to the 7.1 section.

**Comment by Julian** [comment]
@davidism done (probably?)

**Comment by yarikoptic** [comment]
I have ran into this issue as well and would **really** appreciate if upcoming release would carry this fix.  Due to this bug it is really hard to troubleshoot failures!  Thank you in advance!

**Pull request merged**
