### PR TITLE
Fix a couple of typos in the documentation

### PR DESCRIPTION
**Pull request by bast**
Assuming that `master` is the right base for those. If not, I can reapply to another branch or split them up.

### CODE REVIEW

**Comment by marble** [comment]
+1

**Comment by socketpair** [comment]
Hay! why not to merge that ?

**Comment by ThiefMaster** [comment]
Not sure, probably because nobody really noticed the PR

**Comment by bast** [comment]
Thanks! Good to know it went to the right place - wasn't sure anymore :-) Thanks for a great tool!

**Comment by socketpair** [comment]
@ThiefMaster can you scan all opened PR and write an message in each. There are many very good PRs waiting for merging.

**Comment by untitaker** [comment]
Code review takes (free-)time, as opposed to merging typo fixes.

**Pull request merged**
