### PR TITLE
Fix clear() on win, colorama

### PR DESCRIPTION
**Pull request by luw2007**
win10, python2.7, installed click, colorama

```
python
>>>import click;click.clear()
[2J[1;1H>>>
```

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks!

**Comment by untitaker** [comment]
I forgot, could you submit a changelog entry for 4.0 as a separate PR?

**Comment by luw2007** [comment]
I saw you add the changelog on master branch, and there is no branch or tag or Milestones is 4.0
So, Is there any way I can help you?

**Comment by untitaker** [comment]
Click 4.0 is not released yet. At this point there's no clear formulation what needs to be done... I'll add some later.

**Pull request merged**
