### PR TITLE
Escape Sequences with r''

### PR DESCRIPTION
**Pull request by cooperlees**
- Add raw strings to files that have the need so correct escaping occurs

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by cooperlees** [comment]
What's left to do here to get this merged and into the next release? (I'd love not to see these warning when I develop things - When I develop I turn all warnings on)

**Comment by mitsuhiko** [comment]
Thanks!

**Comment by cooperlees** [comment]
Yay. Thanks for merging. Can we expect an easy `6.8` with this or will I be waiting for 7.0?

**Comment by mitsuhiko** [comment]
No, there should be a 6.8.

**Pull request merged**
