### PR TITLE
Add Python 3.7 to test matrix

### PR DESCRIPTION
**Pull request by chbrown**
Python 3.7 was released on 2018-06-27 and is the current version of Python: https://www.python.org/downloads/release/python-370/

### CODE REVIEW

**Comment by chbrown** [comment]
Adding [`dist: xenial`](https://docs.travis-ci.com/user/reference/xenial/#python-support) gets Python 3.7 working, due to a [Trusty vs. OpenSSL incompatibility](https://docs.travis-ci.com/user/languages/python/#development-releases-support):
> Recent Python branches require OpenSSL 1.0.2+. As this library is not available for Trusty, 3.7, 3.7-dev, 3.8-dev, and nightly do not work (or use outdated archive).

...but breaks `pypy` and `pypy3` :(

**Comment by jdufresne** [comment]
You can use `pypy2.7-6.0` and `pypy3.5-6.0` for pypy instead of `pypy` & `pypy3` respectively.

**Comment by chbrown** [comment]
Thanks Jon, that worked! https://travis-ci.org/pallets/click/builds/473416156

**Review by jdufresne — APPROVED** [review]

**Review by kevin-brown — APPROVED** [review]

**Comment by kevin-brown** [comment]
@davidism If you hit "edit" and change the target for this branch to the `7.x` branch, it'll hide the commits that are on `7.x` but haven't made their way to `master`.

**Comment by davidism** [comment]
Closing as we ended up moving to Azure pipelines and address this there.

**Pull request closed without merging**
